---
# Kubernetes 集群主机清单（YAML 格式）
# 根据实际情况修改 IP 地址和主机名

all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    etcd:
      hosts:
        # etcd 集群节点
        etcd:
          ansible_host: 192.168.0.115
          etcd_hostname: 'etcd.k8s.local'

    masters:
      hosts:
        # Kubernetes Master 节点
        master:
          ansible_host: 192.168.0.115
          hostname: 'master.k8s.local'
          etcd_hostname: 'etcd.k8s.local'

    workers:
      hosts:
        # Kubernetes Worker 节点
        # worker1:
        #   ansible_host: 192.168.1.30
        # worker2:
        #   ansible_host: 192.168.1.31
        # worker3:
        #   ansible_host: 192.168.1.32

    # 逻辑分组（示例，通常用于 play 中指定 hosts）
    kube-master:
      children:
        masters:

    kube-node:
      children:
        workers:

    k8s-cluster:
      children:
        masters:
        workers:

  vars:
    # 全局变量
    ansible_ssh_user: root
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    # 如果使用密码认证，取消下面的注释并设置密码
    # ansible_ssh_pass: 'your_password_here'
    # 或者使用 SSH 密钥认证（推荐）
    # ansible_ssh_private_key_file: ~/.ssh/id_rsa
    # etcd 集群主机名配置（全局可用）
    etcd_hostname: 'etcd.k8s.local'
    master_hostname: 'master.k8s.local'